require "active_support/core_ext/integer/time"

# The test environment is used exclusively to run your application's
# test suite. You never need to work with it otherwise. Remember that
# your test database is "scratch space" for the test suite and is wiped
# and recreated between test runs. Don't rely on the data there!

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # While tests run files are not watched, reloading is not necessary.
  config.enable_reloading = false

  # Eager loading loads your entire application. When running a single test locally,
  # this is usually not necessary, and can slow down your test suite. However, it's
  # recommended that you enable it in continuous integration systems to ensure eager
  # loading is working properly before deploying your code.
  config.eager_load = ENV["CI"].present?

  # Configure public file server for tests with Cache-Control for performance.
  config.public_file_server.enabled = true
  config.public_file_server.headers = {
    "Cache-Control" => "public, max-age=#{1.hour.to_i}"
  }

  # Show full error reports and disable caching.
  config.consider_all_requests_local = true
  config.action_controller.perform_caching = false
  config.cache_store = :null_store

  # Render exception templates for rescuable exceptions and raise for other exceptions.
  config.action_dispatch.show_exceptions = :rescuable

  # Disable request forgery protection in test environment.
  config.action_controller.allow_forgery_protection = false

  # Store uploaded files on the local file system in a temporary directory.
  config.active_storage.service = :test

  config.action_mailer.perform_caching = false

  # Added by User for Devise
  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
  ## up to here

  # Tell Action Mailer not to deliver emails to the real world.
  # The :test delivery method accumulates sent emails in the
  # ActionMailer::Base.deliveries array.
  config.action_mailer.delivery_method = :test

  config.action_mailer.smtp_settings ||= {}
  config.action_mailer.smtp_settings[:domain] = "localhost"

  # Print deprecation notices to the stderr.
  config.active_support.deprecation = :stderr

  # Raise exceptions for disallowed deprecations.
  config.active_support.disallowed_deprecation = :raise

  # Tell Active Support which deprecation messages to disallow.
  config.active_support.disallowed_deprecation_warnings = []

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  # config.action_view.annotate_rendered_view_with_filenames = true

  # Raise error when a before_action's only/except options reference missing actions
  config.action_controller.raise_on_missing_callback_actions = true

  ############ Custom settings ############

  # PaperTrail disabled for Test environment (for the sake of efficiency)
  config.after_initialize do
    PaperTrail.enabled = false

    #RoutingFilter.active = false  # Manual says put it in test_helper.rb
  end

  # Read in {#w3c_validate} in /test/test_helper.rb
  # If true (Def: false), the test ignores an error of
  # > An input element with a type attribute whose value is hidden must not have an autocomplete attribute whose value is on or off.
  # which is raised with the HTML generated by Rails 7 default `button_to`.
  # The error started on 2022-10-26 because of a change in the W3C validator
  #   https://github.com/validator/validator/pull/1458
  # where the change is valid in terms of the spec of the HTML form:
  #   https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofilling-form-controls:-the-autocomplete-attribute:autofill-anchor-mantle-2
  # See for the background:
  #  https://stackoverflow.com/questions/74256523/rails-button-to-fails-with-w3c-validator
  config.ignore_w3c_validate_hidden_autocomplete = true
end
